# Generated by Django 3.1.6 on 2021-02-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('cpf', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=17)),
                ('logradouro', models.CharField(max_length=30)),
                ('cidade', models.CharField(max_length=50)),
                ('UF', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('telefone', models.CharField(max_length=17)),
                ('perfil', models.CharField(max_length=1)),
                ('status', models.CharField(max_length=1)),
                ('login', models.CharField(max_length=30)),
                ('senha', models.CharField(max_length=30)),
            ],
        ),
    ]
